### ISSUE TITLE
Dataverse Region + Customer Insights Region must be same

### ISSUE THREAD

**Issue by bstarace** [MicrosoftDocs/customer-insights#14]
Hello - when setting up Customer Insights Sandbox or Production environments while using existing Microsoft Dataverse sharing option, both Dataverse and Customer Insights must exist in same region. If not, deployment of CI will fail.  Specific error here is "the region XXX of the CDS organization is different from the region YYY of instance ID.

Please reflect this in documentation. 

Thank you - 
Brent

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47f39501-6322-e568-9258-bf9c0583fbed
* Version Independent ID: 7d5e220d-7199-811e-43c4-545de3fe38eb
* Content: [Create environments in Customer Insights - Dynamics 365 Customer Insights](https://docs.microsoft.com/en-us/dynamics365/customer-insights/audience-insights/create-environment)
* Content Source: [ci-docs/audience-insights/create-environment.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/audience-insights/create-environment.md)
* Service: **customer-insights**
* Sub-service: **audience-insights**
* GitHub Login: @MichelleDevaney
* Microsoft Alias: **midevane**

**Comment by m-hartmann** [comment]
Hello @bstarace, thank you for reporting the missing information. I've updated the articles that were missing this important prerequisite. You'll see the changes in the published content in the next hours. Hence, I'm closing the issue.

Please continue sharing your feedback. It's super helpful and helps tremendously. 

Kind regards, Michael
