### ISSUE TITLE
The Pre-requisite permission set listed for setting up a synapse export is too broad and does not meet the LPA requirements.

### ISSUE THREAD

**Issue by sanchh** [MicrosoftDocs/customer-insights#15]
The Pre-requisite permission set listed for setting up a synapse export is too broad and does not meet the LPA requirement. 

The permission set can be divided into three categories - 
      1. Set up / create connection, 
      2. Set up Export, 
      3. Query data and run queries in Synapse. 

With some trial and error runs, I was able to complete the above 3 with the following permission sets- 
1. Set up / create connection
   a) Reader permissions to CI SPN and user on RG where synapse ws is created. 
   b) Synapse Administrator permissions to CI SPN and user on synapse ws. 
2. Set up Export
   a) CI admin or contributor role (depending on how the connection has been setup).  
   b) Reader permissions to CI SPN and user on RG where synapse ws is created. 
   c) Synapse Administrator permissions to CI SPN and user on synapse ws. 
3. Query data from Synapse 
   a) For adhoc queries, the user running the queries needs to have “Storage Blob Data Reader” access on CI container customerinsights folder. 
   b) For submitting jobs, synapsews manage identity needs to have “Storage Blob Data Reader” access on CI container customerinsights folder.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 889c047e-f0fb-1919-1e66-072c3167dd0a
* Version Independent ID: b3d73eb4-0207-b460-43a9-3a4d9fe335d9
* Content: [Export Customer Insights data to Azure Synapse Analytics - Dynamics 365 Customer Insights](https://docs.microsoft.com/en-us/dynamics365/customer-insights/audience-insights/export-azure-synapse-analytics)
* Content Source: [ci-docs/audience-insights/export-azure-synapse-analytics.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/audience-insights/export-azure-synapse-analytics.md)
* Service: **customer-insights**
* Sub-service: **audience-insights**
* GitHub Login: @stefanie-msft
* Microsoft Alias: **sthe**

**Comment by m-hartmann** [comment]
@sanchh thank you for reaching out and sharing this information. I'm looking into this with a SME on the product side to make sure we reflect it correctly in the docs. Stay tuned for the update here.

**Comment by m-hartmann** [comment]
@sanchh I'd like to let you know that your suggested changes were clarified in the article and will go live in the next hours. Thanks for taking the time and sharing your findings. I'm closing the issue as it's resolved. Feel free to re-open or create a new one if you have questions. Thanks, Michael

**Comment by sanchh** [comment]
@m-hartmann : Thank you!!
