### ISSUE TITLE
Support for cusom model using new Azure Machine Learning Webservice Endpoint

### ISSUE THREAD

**Issue by sanjaydatasciencedojo** [MicrosoftDocs/customer-insights#16]
Is custom model endpoint only available using classic machine learning? Somehow we are unable to create using new machine learning service.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 27f8d20b-816c-8535-bd34-7d399e47d9a2
* Version Independent ID: 2c7454a9-c9a6-a134-f958-792f4b59f27c
* Content: [Custom machine learning models - Dynamics 365 Customer Insights](https://docs.microsoft.com/en-us/dynamics365/customer-insights/audience-insights/custom-models)
* Content Source: [ci-docs/audience-insights/custom-models.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/audience-insights/custom-models.md)
* Service: **customer-insights**
* Sub-service: **audience-insights**
* GitHub Login: @zacookmsft
* Microsoft Alias: **zacook**

**Comment by m-hartmann** [comment]
Hello @sanjaydatasciencedojo, thanks for reaching out. The endpoint should be available from AML, not only the classic version. Have you [published your pipeline under a pipeline endpoint](https://docs.microsoft.com/en-us/azure/machine-learning/how-to-run-batch-predictions-designer#consume-an-endpoint) that the custom model in CI can access? 
Thanks, 
Michael

**Comment by m-hartmann** [comment]
Hi @sanjaydatasciencedojo, I'm closing the issue because I didn't hear back. Feel free to reopen or create a new one if you still have questions. Thanks :) Michael
