### ISSUE TITLE
CI Data Environment - Azure Data Lake Storage 

### ISSUE THREAD

**Issue by RJGRSMOnGitHub** [MicrosoftDocs/customer-insights#18]
Hi Michael, @m-hartmann 

Quick question - can we elect data lake storage for the storage and still run the OOB predictions?

We would prefer to put data in the ADL and run transactional churn or subscription churn from there.

Thank you for your kind attention and assistance.

**Comment by m-hartmann** [comment]
Hi @RJGRSMOnGitHub, thanks for reaching out. I'm checking with the team on this. Please stay tuned. 
Thanks, 
Michael

**Comment by zacookmsft** [comment]
Hi @RJGRSMOnGitHub!

You can! Your data at rest will stay in your own lake. During processing, data will be processed through your Customer Insights instance in the Microsoft subscription, and the results will be written back again to your lake. Hope that helps!
Cheers!
-Zach

**Comment by m-hartmann** [comment]
Thank you for the confirmation, Zach. I'm closing the issue. Feel free to open a new one if you have additional questions. 
Thanks, 
Michael

**Comment by RJGRSMOnGitHub** [comment]
Thank you Zach and Michael! Great news!
