### ISSUE TITLE
Customer Insights DateTime Transforms Power Query Error

### ISSUE THREAD

**Issue by RJGRSMOnGitHub** [MicrosoftDocs/customer-insights#19]
Hi @zacookmsft and @m-hartmann,

Is there anyone on the CI team that specializes in PQ Connector questions? We have a DateTime Transform problem. "The M query of section contact does not have the Customer Insights DateTime custom transforms"; so far a dead end on finding the real answer.

This is occurring on the created and modified on columns on the ingestion of the contact entity.

Best,

Ron

**Comment by zacookmsft** [comment]
Hi Ron!

It would be helpful to know how you encountered the error. Is this a brand new datasource you're creating? Or are you editing a current datasource? Can you help me understand the steps you took before you saw the error?

Thanks!
-Zach
