### ISSUE TITLE
In Prerequisites section link to Microsoft Dataverse returns a 404

### ISSUE THREAD

**Issue by saviegas** [MicrosoftDocs/customer-insights#20]
In Prerequisites section link to Microsoft Dataverse returns a 404

Audience insights profiles must be stored in an Azure Data Lake Storage account that you own, or in a [Microsoft Dataverse](https://docs.microsoft.com/en-us/powerapps/maker/data-platform/data-platform-intro.md)–managed data lake.

Not sure if correct link should be:
https://docs.microsoft.com/en-us/powerapps/maker/data-platform/data-platform-intro

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b2ab19a0-907c-272b-36dc-15db4e943f36
* Version Independent ID: 0a875890-492d-51a6-4565-24ae6e68a383
* Content: [Create a link between audience insights and engagement insights - Dynamics 365 Customer Insights](https://review.docs.microsoft.com/en-us/dynamics365/customer-insights/engagement-insights/integrate-audience-insights-engagement-insights?source=docs&branch=main)
* Content Source: [ci-docs/engagement-insights/integrate-audience-insights-engagement-insights.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/engagement-insights/integrate-audience-insights-engagement-insights.md)
* Service: **customer-insights**
* GitHub Login: @mkisel
* Microsoft Alias: **mkisel**

**Comment by m-hartmann** [comment]
Thanks for letting me know @saviegas ! The fix is pushed and will publish shortly. Thanks!
