### ISSUE TITLE
PLease add information on "advanced reporting"

### ISSUE THREAD

**Issue by johannes-wagner-itvt** [MicrosoftDocs/customer-insights#21]
Since recently you can select a Power BI capactity when setting up an environment. Please add information on this into the documentation.
![image](https://user-images.githubusercontent.com/29097697/154650818-7e69d169-c20e-478d-9c71-f979748006c3.png)

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38653a9d-7a8d-79d7-3584-278d6e5baa7a
* Version Independent ID: 3da3e006-f7bc-84ef-9c4c-999586ed409e
* Content: [Create and manage environments - Dynamics 365 Customer Insights](https://docs.microsoft.com/en-us/dynamics365/customer-insights/audience-insights/manage-environments)
* Content Source: [ci-docs/audience-insights/manage-environments.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/audience-insights/manage-environments.md)
* Service: **customer-insights**
* Sub-service: **audience-insights**
* GitHub Login: @NimrodMagen
* Microsoft Alias: **nimagen**

**Comment by m-hartmann** [comment]
@johannes-wagner-itvt Thank you for reporting the issues. I'm looking into this with the team and will update this thread as soon as I have more information. 

Thanks, 
Michael

**Comment by m-hartmann** [comment]
@johannes-wagner-itvt the feature on Power BI capacity was removed from the environment creation flow again and the team looks for a less disruptive way to let users with a lot of profile data designate a Power BI capacity to build custom reports on CI entities. Please stay tuned for future announcements. I'm closing the issue for now. Please open a new issue if you find information missing in docs. 

Thanks, 
Michael
