### ISSUE TITLE
Qusetion about "user"

### ISSUE THREAD

**Issue by pouelletcoopgit** [MicrosoftDocs/customer-insights#23]
[Enter feedback here]
There are references to a "user" in the below steps, but I don't see where it explains what that user is.

On the resource group the Azure Synapse workspace is located, the service principal and the user for audience insights needs to be assigned at least Reader permissions. For more information, see [Assign Azure roles using the Azure portal](https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-portal).

The user needs Storage Blob Data Contributor permissions on the Azure Data Lake Storage Gen2 account where the data is located and linked to the Azure Synapse workspace. Learn more about [using the Azure portal to assign an Azure role for access to blob and queue data](https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac-portal) and [Storage Blob Data Contributor permissions](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#storage-blob-data-contributor).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 889c047e-f0fb-1919-1e66-072c3167dd0a
* Version Independent ID: b3d73eb4-0207-b460-43a9-3a4d9fe335d9
* Content: [Export Customer Insights data to Azure Synapse Analytics - Dynamics 365 Customer Insights](https://docs.microsoft.com/en-us/dynamics365/customer-insights/audience-insights/export-azure-synapse-analytics)
* Content Source: [ci-docs/audience-insights/export-azure-synapse-analytics.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/audience-insights/export-azure-synapse-analytics.md)
* Service: **customer-insights**
* Sub-service: **audience-insights**
* GitHub Login: @stefanie-msft
* Microsoft Alias: **sthe**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pouelletcoopgit. This issue has been assigned to the doc author for review.

**Comment by m-hartmann** [comment]
Hello @pouelletcoopgit, thank you for sharing your feedback. Would it be clearer to you if we'd refer to "an Azure AD user who can access both, Azure services and Customer Insights"?

Happy to dig into this more with the SME on the product side and follow up after hearing your feedback.

Thanks, 
Michael

**Comment by pouelletcoopgit** [comment]
Hi!

If the reference to "the user" is meant to explain that in order to set permissions in azure, you need an azure user with the ability to set permissions on those objects then maybe adding it as a preface to the steps would make more sense?

In essence we are setting customer insights service principal access to the synapse workspace resource group, datalake etc. Adding reference to another user in those steps is what may add confusion.

Thanks.

Patrick Ouellet | Solution Designer - Technology
Cloud and Hosting Services | Groupe Co-operators limitée
2875 Boul Laurier D3-501, Québec (Québec)  G1V 2M2
Tél. : 418-934-0584 | Numéro sans frais : 1-855-850-2667, poste 313000
[Co-operators Logo]

**Comment by m-hartmann** [comment]
Hello Patrick, 

thank you for getting back to us. We tweaked the documentation to refer more clearly to the required user permissions for the AD user that is setting up the export as well as the service principal. I hope this clarifies the requirements and reduces confusion. 

Btw, I edited your email response above and removed your personal details from the message because it's accessible for everyone.

Please reopen the issue or create a new one if you think the content is still unclear.

Thanks!
Michael
