### ISSUE TITLE
Lack of information for Prerequisites

### ISSUE THREAD

**Issue by DavidPaf** [MicrosoftDocs/customer-insights#26]
To follow the tasks, you must first select Primary target audience ( top left-side menu) to: Individual consumers. If not, you cannot select Product recommendations in TASK 3.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @DavidPaf. This issue has been assigned to the doc author for review.

**Comment by m-hartmann** [comment]
Thank you for sharing the feedback. The article was updated accordingly and the changes will show in the live site shortly. 

Thanks, 
Michael
