### ISSUE TITLE
Task 3 - Configure product recommendation prediction is not updated

### ISSUE THREAD

**Issue by DavidPaf** [MicrosoftDocs/customer-insights#27]
Hi team,

Seem there is incorrect context for TASK 3 at [Sample Guide](https://docs.microsoft.com/en-us/dynamics365/customer-insights/sample-guide-predict-product-recommendation#task-3---configure-product-recommendation-prediction)

_With the unified customer profiles in place, we can now run the subscription churn prediction._

Is the current task for Product recommendation?

Also, steps number 5 is out of date, the steps are difference.

_5. Select Required data and select Add data for purchase history._

Kindly review and update the document to latest version of Customer Insight. I am trying to prepare a demo of Product Recommendation using CI. the demo version does not contain ready-to-use Product Recommendation train.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @DavidPaf. This issue has been assigned to the doc author for review.

**Comment by m-hartmann** [comment]
Thank you for spotting this @DavidPaf 

I've fixed the references and we're working on getting the steps updated to the latest version. Stay tuned!

**Comment by DavidPaf** [comment]
Hello Michael,

Thank you for the quick review.

Can I have preview the steps for that as I am going to  have a Product recommendations demo to our client tomorrow.

Regards,

David Nguyen


________________________________

**Comment by m-hartmann** [comment]
I'm working with the feature owner on validating the steps and drafting the updates. They are not yet available for preview. If you are a colleague at Microsoft, please ping me (mhart) through Teams for a quick chat.

**Comment by m-hartmann** [comment]
Hello David, 

I've made some updates to the sample guide to ensure the model runs and produces results with the sample data provided. Feel free to have a look and let me know if it's not working for you. https://docs.microsoft.com/en-us/dynamics365/customer-insights/sample-guide-predict-product-recommendation

I'm closing the issue and invite you to reopen it or ping me on Teams if you have additional questions. 

Thanks, 
Michael
