### ISSUE TITLE
Customer and support team feedback: Use 'Choose columns' instead of SELECT in ODATA / CI 

### ISSUE THREAD

**Issue by Scott-Stabbert** [MicrosoftDocs/customer-insights#30]
Hi Michael,
Multiple customers have stated using OData with Select statements in URL creates corrupted table entities. 
I was reviewing a customer support incident, and thought the resolution should be updated in our docs...
Recommend reviewing content with someone who understands OData better and see if the sample code needs to be updated.

Customer verbatim:

> OData Select Issue
> In our Odata queries we used the select function within the URL to pick which fields we want
> However, a lot of our queries were going corrupt, so I had to work with support
> They noticed that the queries were using the select function and actually had a different client recently have the same issue
> The fix was to remove the select from the URL and instead use the Choose Columns step in the query
> After doing the corrupt table was removed

Example:
let
Source = OData.Feed("https://{pii}.crm.dynamics.com/api/data/v9.1/{entityNamePii}", null, [Implementation = "2.0"]),
#"Choose columns" = Table.SelectColumns(Source, {"columns1", "columns2", "columns3"}),

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ff70c45-490f-f6e1-651f-5b3d67f0b50b
* Version Independent ID: 9ff70c45-490f-f6e1-651f-5b3d67f0b50b
* Content: [OData examples for the Dynamics 365 Customer Insights APIs - Dynamics 365 Customer Insights](https://docs.microsoft.com/en-us/dynamics365/customer-insights/odata-examples)
* Content Source: [ci-docs/odata-examples.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/odata-examples.md)
* Service: **customer-insights**
* Sub-service: **audience-insights**
* GitHub Login: @m-hartmann
* Microsoft Alias: **mhart**

**Comment by m-hartmann** [comment]
Ack, thanks Scott! I'll follow up offline and close the issue in the public repo.
