### ISSUE TITLE
Additional permission needed to Mention in the ADLS account Connection 

### ISSUE THREAD

**Issue by piyushzope** [MicrosoftDocs/customer-insights#31]
There are a few additional permission needed to mention in this document. 

Scenario:
When we were creating the Instance in Customer Insights and the Customer wanted to use the ADLS Account as Storage. 
We told the Customer to create a Storage Account who automatically became the owner of that account. 
And asked to give the Service Principal Access (Dynamics 365 AI for Customer Insights) as Storage Blob Data Contributor, but when we tried to connect the ADLS account on the Create Environment step it gave us the error and dint created the Environment.

Error:  Unauthorized access to perform operation for container 'customerinsights'. Please obtain the right access permissions and try again.

Solution: **We added the storage blob reader access on the container to the user who was creating the Environment. Which worked and we successfully create the Environment.**

Another thing that I observed while looking for resource details in the Azure Portal.
The Document says that I have to go to Storage Account and look for Properties under the settings. 
**But there is no Properties button it should be Endpoints**

----------
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 447e1566-ce81-f273-f049-8c53fa84f65f
* Version Independent ID: 447e1566-ce81-f273-f049-8c53fa84f65f
* Content: [Connect to an Azure Data Lake Storage account by using a service principal - Dynamics 365 Customer Insights](https://docs.microsoft.com/en-us/dynamics365/customer-insights/connect-service-principal)
* Content Source: [ci-docs/connect-service-principal.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/connect-service-principal.md)
* Service: **customer-insights**
* Sub-service: **audience-insights**
* GitHub Login: @adkuppa
* Microsoft Alias: **adkuppa**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @piyushzope. This issue has been assigned to the doc author for review.

**Comment by m-hartmann** [comment]
Hello @piyushzope - thank you for sharing the feedback. We're already working on an update for the environment creation docs and specify the role requirements for the container in ADLS more clearly. I'll update here when we have the changes rolled out. 
Thanks!
Michael

**Comment by m-hartmann** [comment]
Hello again, @piyushzope - wanted to close the loop here that we published an update to the docs that mention the role requirements more clearly: https://docs.microsoft.com/en-us/dynamics365/customer-insights/own-data-lake-storage

I'm closing this issue but feel free to reopen it if you still find things off or open a new one if you have additional feedback. 

Many thanks!
Michael
