### ISSUE TITLE
Error in text

### ISSUE THREAD

**Issue by pedroboareto** [MicrosoftDocs/customer-insights#32]
Hi,

In "Look for an existing service principal" the stage 3 "manage"is wrong!

It's written "select Enterprise Applications" and actually should be "select Microsoft Application"

I spend two weeks not understanding why I could not install this Service Principal because I never found in the AD. And the answer is that the documentation is wrong

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 447e1566-ce81-f273-f049-8c53fa84f65f
* Version Independent ID: 447e1566-ce81-f273-f049-8c53fa84f65f
* Content: [Connect to an Azure Data Lake Storage account by using a service principal - Dynamics 365 Customer Insights](https://docs.microsoft.com/en-us/dynamics365/customer-insights/connect-service-principal?source=docs)
* Content Source: [ci-docs/connect-service-principal.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/connect-service-principal.md)
* Service: **customer-insights**
* Sub-service: **audience-insights**
* GitHub Login: @adkuppa
* Microsoft Alias: **adkuppa**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pedroboareto. This issue has been assigned to the doc author for review.
