### ISSUE TITLE
Unable to see Incremental refresh options in Dynamic365 Customer Insights 

### ISSUE THREAD

**Issue by kulbhushankatoch** [MicrosoftDocs/customer-insights#37]
Hi 

We are trying to set up incremental refresh as per Microsoft documentations, but we did not see these option being enabled in Dynamic365 Customer Insights Business Applications.

Below is screenshot from Production Environment:
![image](https://user-images.githubusercontent.com/24887416/182787576-4f4eeaa5-f5d4-4c94-bde2-1e3b800f97e0.png)

Regards
Kulbhushan
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e5948445-354f-bafe-52f5-c2f0913bc8b2
* Version Independent ID: e5948445-354f-bafe-52f5-c2f0913bc8b2
* Content: [Enrichment for data sources (preview) - Dynamics 365 Customer Insights](https://docs.microsoft.com/en-us/dynamics365/customer-insights/data-sources-enrichment)
* Content Source: [ci-docs/data-sources-enrichment.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/data-sources-enrichment.md)
* Service: **customer-insights**
* Sub-service: **audience-insights**
* GitHub Login: @NimrodMagen
* Microsoft Alias: **nimagen**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @kulbhushankatoch. This issue has been assigned to the doc author for review.

**Comment by m-hartmann** [comment]
@kulbhushankatoch thanks for submitting the issue. I reached out to the product team for clarification. To confirm, the data source is of type Power Query of Azure Data Lake?

Thanks, 
Michael

**Comment by mukeshpo** [comment]
@kulbhushankatoch  - is this still an issue? you likely encountered while this was being rolled out to all the regions. if you still see the option for incremental data ingestion missing, pls log a support ticket http://aka.ms/cisupport
