### ISSUE TITLE
CI - Delete request for specific data records

### ISSUE THREAD

**Issue by harishajabe1** [MicrosoftDocs/customer-insights#39]
Hello Team,

To implement GDPR for CI, you have mentioned to delete data at source and perform complete refresh (section: Manage requests to delete customer data). We don't want to perform complete refresh instead we are looking for option to delete specific data from CI without performing complete refresh. We didn't find any such option in this page. 
Can you please let us know if there is any such option available? or if you have any page which explain about this option, please let's know that page link.

- Harish
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 450a92c5-5f34-2fdd-2525-979132495b1b
* Version Independent ID: 2d740423-73a3-5eea-00bc-54f323acc996
* Content: [Data Subject Rights (DSR) requests under GDPR - Dynamics 365 Customer Insights](https://docs.microsoft.com/en-us/dynamics365/customer-insights/dsr-rights-requests)
* Content Source: [ci-docs/dsr-rights-requests.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/dsr-rights-requests.md)
* Service: **customer-insights**
* Sub-service: **audience-insights**
* GitHub Login: @m-hartmann
* Microsoft Alias: **wimohabb**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @harishajabe1. This issue has been assigned to the doc author for review.

**Comment by m-hartmann** [comment]
Hello @harishajabe1 - there's no such feature available in CI. Removing data from CI works as you pointed out, by deleting it on the source and refreshing the data in CI without the deleted data.

However, feel free to suggest this feature to the product team on the [Ideas site](https://experience.dynamics.com/ideas/categories/?forum=79a8c474-4e35-e911-a971-000d3a4f3343&forumName=Dynamics%20365%20Customer%20Insights). 

Thanks, Michael
