### ISSUE TITLE
Customer Insights DateTime Custom Transforms

### ISSUE THREAD

**Issue by lphomiej** [MicrosoftDocs/customer-insights#4]
I got an error when trying to import data:

**Couldn't create data source

The M query of section 'Account' does not have the Customer Insights DateTime custom transforms. Please undo these changes before saving.** 

There doesn't seem to be any documentation about requiring certain transforms - ie: "Customer Insights Datetime custom transforms" - anywhere...

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e9abcdb-de06-6a01-a206-e2d5b48cac33
* Version Independent ID: aae383af-89b1-88b8-ffd2-fbd188eb5566
* Content: [Use data sources to ingest data - Dynamics 365 Customer Insights](https://docs.microsoft.com/en-us/dynamics365/customer-insights/audience-insights/data-sources)
* Content Source: [ci-docs/audience-insights/data-sources.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/audience-insights/data-sources.md)
* Service: **customer-insights**
* Sub-service: **audience-insights**
* GitHub Login: @adkuppa
* Microsoft Alias: **adkuppa**

**Comment by m-hartmann** [comment]
Hi Jeff, thanks for reaching out. 
This transformation is supposed to get added automatically by the system and the team needs a few more details specific to your environment to analyze the issue. Please [open a support ticket](https://go.microsoft.com/fwlink/?linkid=2079641) so our team can look into what's going wrong here. 
If that worked for you, kindly drop me a note here so I can close this issue. 

Sincerely, 
Michael (Tech writer for Customer Insights)

cc @adkuppa

**Comment by m-hartmann** [comment]
Closing the issue, assuming the support option can help resolve it. Please reopen or create new issue if this doesn't succeed.

Thanks, 
Michael
