### ISSUE TITLE
What is admin? 

### ISSUE THREAD

**Issue by mwasham** [MicrosoftDocs/customer-insights#41]
[Enter feedback here]
You should add the steps to get to "Admin" 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 020396b1-9bf5-25da-1744-9bfa11cd711c
* Version Independent ID: 020396b1-9bf5-25da-1744-9bfa11cd711c
* Content: [Export segments to Dynamics 365 Sales (preview) - Dynamics 365 Customer Insights](https://learn.microsoft.com/en-us/dynamics365/customer-insights/export-dynamics365-sales)
* Content Source: [ci-docs/export-dynamics365-sales.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/export-dynamics365-sales.md)
* Service: **customer-insights**
* Sub-service: **audience-insights**
* GitHub Login: @pkieffer
* Microsoft Alias: **philk**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mwasham. This issue has been assigned to the doc author for review.

**Comment by m-hartmann** [comment]
As I haven't head back, I'll add this refinement as a consideration for future updates. We'll look into calling out specifically how to get to a certain area in a future update. In the meantime, I'll close this issue. Please reopen or create a new one if you have further feedback.

Thanks,
Michael
