### ISSUE TITLE
Add more clarity to section "Claim ownership of an environment"

### ISSUE THREAD

**Issue by mattmblackmore** [MicrosoftDocs/customer-insights#46]
Hi,

Would it be possible to add some additional detail to the section entitled "Claim ownership of an environment" to make it clear that we recommend customers have more than one admin in an instance? as this process to claim ownership is only possible if there is already another admin present. 

We recently had a support case where the customer only had one admin in the instance, so feel it would be good to make the recommendation about multiple admins in case an owner leaves.

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 84db51ba-5e64-cfd6-9e07-e97339c1dd3b
* Version Independent ID: 84db51ba-5e64-cfd6-9e07-e97339c1dd3b
* Content: [Manage environments - Dynamics 365 Customer Insights](https://learn.microsoft.com/en-us/dynamics365/customer-insights/manage-environments#claim-ownership-of-an-environment)
* Content Source: [ci-docs/manage-environments.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/manage-environments.md)
* Service: **customer-insights**
* GitHub Login: @mukeshpo
* Microsoft Alias: **mukeshpo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @mattmblackmore. This issue has been assigned to the doc author for review.
