### ISSUE TITLE
Not clear _how_ to share data sources

### ISSUE THREAD

**Issue by pieterh** [MicrosoftDocs/customer-insights#48]
Hi,
The documentation states: 
"Shared: Data sources that can be managed by all Customer Insights admins. Power Platform dataflows, your own storage account, and attaching to a Dataverse-managed data lake are examples of shared data sources."

The documentation is not clear about how to share a data source and we are not able to find an option in CI to do so. Could you update the documentation to make clear how to share data sources?

Kind Regards,
Pieter Hilkemeijer

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cda22ec8-07f8-7f1b-b67a-128ad4c9a347
* Version Independent ID: cda22ec8-07f8-7f1b-b67a-128ad4c9a347
* Content: [Data sources overview - Dynamics 365 Customer Insights](https://learn.microsoft.com/en-gb/dynamics365/customer-insights/data-sources)
* Content Source: [ci-docs/data-sources.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/data-sources.md)
* Service: **customer-insights**
* GitHub Login: @mukeshpo
* Microsoft Alias: **mukeshpo**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @pieterh. This issue has been assigned to the doc author for review.

**Comment by m-hartmann** [comment]
Hi Pieter @pieterh, 
thank you for raising the issue. The sharing option is getting removed shortly as it depends on other services that we can't control via the Customer Insights UI. Data sources will be either managed by me or managed by others and owners would need to make ownership changes in the origin of the data source. 

I'm closing this issue for now and invite you to reopen it for more feedback or create a new one. 

Thanks, 
Michael
