### ISSUE TITLE
For Permission type, select Application permissions and then select the CustomerInsights.Api.All permission - DOES NOT EXIST

### ISSUE THREAD

**Issue by semberley** [MicrosoftDocs/customer-insights#49]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 6343d051-c808-d9a6-8d56-8a6b3bcc8ab6
* Version Independent ID: 6343d051-c808-d9a6-8d56-8a6b3bcc8ab6
* Content: [Work with Customer Insights APIs - Dynamics 365 Customer Insights](https://learn.microsoft.com/en-us/dynamics365/customer-insights/apis#server-to-server-application-permissions)
* Content Source: [ci-docs/apis.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/apis.md)
* Service: **customer-insights**
* GitHub Login: @m-hartmann
* Microsoft Alias: **wimohabb**

**Comment by m-hartmann** [comment]
@semberley thanks for raising this issue. Looks like the permission name was changed to **api.access**. Please try that permission and re-open this issue if it's not showing for you. In the meantime, I get the article updated and republished, which will automatically close this issue.

Thanks, 
Michael
