### ISSUE TITLE
Export result in D365 Sales ?

### ISSUE THREAD

**Issue by tbienvenu** [MicrosoftDocs/customer-insights#5]
This sounds very interesting.
Which table will be created in the Dynamics 365 for Sales Dataverse after the export?
How are the tables updated when the segment is updated (full delete and recreate, delete/insert changes only)?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 167d8a4b-8acd-742b-fb4c-e11df01cd984
* Version Independent ID: a1d52790-53da-67ee-2e3c-701ce6d74c6e
* Content: [Export Customer Insights data to Dynamics 365 Sales - Dynamics 365 Customer Insights](https://docs.microsoft.com/en-us/dynamics365/customer-insights/audience-insights/export-dynamics365-sales)
* Content Source: [ci-docs/audience-insights/export-dynamics365-sales.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/audience-insights/export-dynamics365-sales.md)
* Service: **customer-insights**
* Sub-service: **audience-insights**
* GitHub Login: @phkieffer
* Microsoft Alias: **philk**

**Comment by m-hartmann** [comment]
Hello @tbienvenu - thanks for reaching out. I want to acknowledge that I received your question and let you know that I need to follow up with a team member on the details before sharing a conclusive answer. Please stay tuned. 

Thanks, 
Michael

**Comment by pkieffer** [comment]
Hi @tbienvenu - thanks for reaching out. 

Currently, there's no update to tables in user-managed Dataverse environments after the export. The updates are written into a managed Data Lake and made available through the user interface of the Sales app. While the information in the managed Data Lake will be update with every refresh of the segment, you can't access those tables in the Dataverse directly.

Please don't hesitate to reach out in case you have additional questions. 

Thanks, 
Phil

**Comment by m-hartmann** [comment]
Thank you Phil for the reply. Closing the issue, assuming your answer clarifies the question. Please reopen or create a new issue if there are additional questions. 

Thanks, 
Michael
