### ISSUE TITLE
Go to Admin > Security and select the APIs tab - There is no such area; Admin > Security does not exist in the CI interface

### ISSUE THREAD

**Issue by semberley** [MicrosoftDocs/customer-insights#50]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 968a61b9-0400-1b8a-7c18-011267ccb3cb
* Version Independent ID: 968a61b9-0400-1b8a-7c18-011267ccb3cb
* Content: [Manage Customer Insights APIs - Dynamics 365 Customer Insights](https://learn.microsoft.com/en-us/dynamics365/customer-insights/apis-manage)
* Content Source: [ci-docs/apis-manage.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/apis-manage.md)
* Service: **customer-insights**
* GitHub Login: @wimohabb
* Microsoft Alias: **wimohabb**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @semberley. This issue has been assigned to the doc author for review.

**Comment by m-hartmann** [comment]
@semberley thank you for sharing. I'll get the outdated click paths updated. API usage is under System > Settings and API permissions under System > Permissions. 

When I merge the PR with the changes, this issue gets closed automatically. Please open new issues if you spot other doc issues. 

Thanks, 
Michael
