### ISSUE TITLE
Missing relationship information for Website Review activity in Task 3

### ISSUE THREAD

**Issue by semberley** [MicrosoftDocs/customer-insights#52]
To complete the website review activity, we need to create a relationship to another table.  The task is missing to what table you expect us to create a relationship to AND what fields to use.

The activity cannot be saved without this relationship.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 4da05ce6-4723-2ebc-8019-295d7b43f510
* Version Independent ID: 4da05ce6-4723-2ebc-8019-295d7b43f510
* Content: [Customer lifetime value (CLV) prediction sample guide - Dynamics 365 Customer Insights](https://learn.microsoft.com/en-us/dynamics365/customer-insights/sample-guide-predict-clv)
* Content Source: [ci-docs/sample-guide-predict-clv.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/sample-guide-predict-clv.md)
* Service: **customer-insights**
* GitHub Login: @yashlundia
* Microsoft Alias: **yalundia**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @semberley. This issue has been assigned to the doc author for review.

**Comment by v-wendysmith** [comment]
Hello @semberley . Thanks for your feedback! I'm contacting the product team to provide additional information to add to the documentation. I'll let you know when I have a timeframe on when the update will be published.  Thanks.

**Comment by v-wendysmith** [comment]
Hello @semberley. We will have the doc updated by the end of the month. Thanks again for your feedback.

**Comment by v-wendysmith** [comment]
Doc was updated: https://learn.microsoft.com/en-us/dynamics365/customer-insights/data/sample-guide-predict-clv

**Comment by bishalgoswami** [comment]
Thanks for your comment, @semberley. This issue has been assigned to the doc author for review.

**Comment by m-hartmann** [comment]
Closing this as completed.
