### ISSUE TITLE
Add info on whether permissions are live right away after 'Save', need browser refresh, log out/in etc

### ISSUE THREAD

**Issue by raoulteeuwenPE** [MicrosoftDocs/customer-insights#54]
Kindly request adding (on any page about changing permissions) info on on whether logged-in users should experience the change right away, or they need to refresh their browser, need to log out/in (re-authenticate) and/or something else.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: c15d5cf2-b5cc-01cd-03d4-e9f8bf6750fc
* Version Independent ID: c15d5cf2-b5cc-01cd-03d4-e9f8bf6750fc
* Content: [Assign user permissions - Dynamics 365 Customer Insights](https://learn.microsoft.com/en-us/dynamics365/customer-insights/permissions)
* Content Source: [ci-docs/permissions.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/permissions.md)
* Service: **customer-insights**
* GitHub Login: @NimrodMagen
* Microsoft Alias: **nimagen**

**Comment by bishalgoswami** [comment]
Thanks for your comment, @raoulteeuwenPE. This issue has been assigned to the doc author for review.

**Comment by m-hartmann** [comment]
Hello @raoulteeuwenPE - I've queued a fix to clarify that in docs that goes live in a few days. After speaking with the product team, I want to share here too. It can take up to 15 minutes to fully propagate the changes to permissions. To see changes reflected in the user interface, users should refresh the browser window that runs the application.

I'm closing the issue but feel free to open a new one or reopen it if you have additional questions. 

Thanks, 
Michael
