### ISSUE TITLE
Need to give access at the container level

### ISSUE THREAD

**Issue by tbienvenu** [MicrosoftDocs/customer-insights#7]
To be able to see the contents of the CDM folder, I had to add the rights at the container level in the Datalake. Is this specific to my environment or does the documentation need to be updated?
![screenshot 2306](https://user-images.githubusercontent.com/17125637/123656986-aef12080-d830-11eb-8109-3428e9caa24d.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 650d0a04-539d-cfad-98cf-2f5ecff2e05f
* Version Independent ID: ea10d470-a231-86a2-cddd-d03abf249ca7
* Content: [Connect to an Azure Data Lake Storage Gen2 account with a service principal - Dynamics 365 Customer Insights](https://docs.microsoft.com/en-us/dynamics365/customer-insights/audience-insights/connect-service-principal#create-azure-service-principal-for-audience-insights)
* Content Source: [ci-docs/audience-insights/connect-service-principal.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/audience-insights/connect-service-principal.md)
* Service: **customer-insights**
* Sub-service: **audience-insights**
* GitHub Login: @adkuppa
* Microsoft Alias: **adkuppa**

**Comment by adkuppa** [comment]
Hello tbienvenu,

The above documentation link refer to the administration of a CI environment and connect to Azure resources using service principal access like connecting to the storage account etc. It does not mention connecting to the storage account in data sources. In this [documentation ](https://docs.microsoft.com/en-us/dynamics365/customer-insights/audience-insights/connect-common-data-model#connect-to-a-common-data-model-folder), we also mention the roles the user creating the data sources should have i.e.,  either of the storage blob data reader/contributor/owner permissions, along with granting CI service principal access.

Please let us if additional information is needed.

Thank you!
Aditya Kuppa
Customer Insights team
