### ISSUE TITLE
OBM vs RTJ Event Feature Table Update - Custom Registration Field

### ISSUE THREAD

**Issue by crmpatrick** [MicrosoftDocs/customer-insights#76]
https://learn.microsoft.com/en-us/dynamics365/customer-insights/journeys/event-management#when-to-use-customer-insights---journeys-and-when-to-use-outbound-marketing-for-event-management

This table should include a row regarding Custom Registration Fields.

**Comment by bishalgoswami** [comment]
Thanks for your comment, @crmpatrick. This issue has been assigned to the doc author for review.

**Comment by crmpatrick** [comment]
[like]  Patrick Wright reacted to your message:
________________________________

**Comment by m-hartmann** [comment]
Thanks for the feedback, @crmpatrick -- @alfergus This one's for you (CIJ)

**Comment by alfergus** [comment]
Hi @crmpatrick -- I'm adding a row to the table now. As you likely surmised, [custom registration field](https://learn.microsoft.com/en-us/dynamics365/customer-insights/journeys/custom-registration-fields-outbound) functionality was in outbound marketing but is not yet available for real-time journeys. The feature is planned in real-time journeys pipeline for 2024.

**Comment by crmpatrick** [comment]
[like]  Patrick Wright reacted to your message:
________________________________
