### ISSUE TITLE
Showing "[!div class="mx-imgBorder"]"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/customer-insights#8]
en-us: "https://docs.microsoft.com/en-us/dynamics365/customer-insights/audience-insights/sample-guide-predict-transactional-churn"
![sample-guide-predict-transactional-churn_e](https://user-images.githubusercontent.com/40815708/127730650-fc45d56f-efa4-41c3-9629-2d073a96c26c.png)

#PingMSFTDocs

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e2065c4-2352-9798-26bb-f1e3577bcb98
* Version Independent ID: ecaf414a-0916-389e-8347-ab053ceaea86
* Content: [Transactional churn prediction sample guide - Dynamics 365 Customer Insights](https://docs.microsoft.com/en-us/dynamics365/customer-insights/audience-insights/sample-guide-predict-transactional-churn)
* Content Source: [ci-docs/audience-insights/sample-guide-predict-transactional-churn.md](https://github.com/MicrosoftDocs/customer-insights/blob/main/ci-docs/audience-insights/sample-guide-predict-transactional-churn.md)
* Service: **customer-insights**
* Sub-service: **audience-insights**
* GitHub Login: @diegogranados117
* Microsoft Alias: **digranad**

**Comment by m-hartmann** [comment]
Thank you for reporting the issue @hyoshioka0128. It's fixed now and the div tag is no longer showing. 

Please keep your feedback coming. I'll close this issue and look forward to hearing from you again.
